apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongosecret
  namespace: pablogarin
spec:
  encryptedData:
    secret: AgDkH40dn6CYjSS+ca0/QCth6oYhGH6o0t7BgAQkBz/FyX6N7tLbuqBbbA3ydapc3sjwe4bAtuXr9HbFVUDEUIjp/vpkSBC57EX0aHT94qeho+fRbgERmouEboTP1ckcVWP598+2YD2hZqaovxi93MYTBmLXUaJVRK+F0SovasdodfrnZ0IYOW84PA6k1EU+wNE3hxfsiI6yhQgKH6l/QdzcpbBngXOZvSZvyvUZzopvw6pO3wCYud9HzGPie3alW30IRtr6SfyLSZKVpykO3U/oMifXHIL8zYAGCd4mQhnpjzUDaT5Ck/5nPGOPWgckJ/YPnTzYGJY15b/jyUyLQZkb2LviA37j1IsJVXKJ/GX0Ecez7gTKk2gO23LtdJdIXep6PMXpDnTRAGAxxNwKbKo+StDeaIGQ/9d3k7rOGXpGcH+UYXrUeqhGo/8L8FK7murpZ+8LBuc66k2DV3i/97unkI6UHdbiufejc78n+G9cUDrtGfn23Z+c0oH21AgYH2w6j91gGZYbcFr5M9oOrdsQCzUwfGio7maTCODfuMI7aSm2Fj4hAjB4JoBfF5vuZlnxFrg3e0JRPyfRfhA/D0SbuFPvCkCPnUbpCpHBaTZClrOAxFW9G+IzFnvfltl22iiBfNcDodeLxxsMARQ3ADvIJ+ywF0eE5hFFEk5A47f+ULURfGF+kBzuK58XOwpInk7v0O1s9YbvAmSjcuz6Yyj5RGCQosp+YOLn+95XSSLx42G9H73ub9ac8CBraYNoOCKOjONyRMG4V1gdkaHYG79OhiwPZAlnmY2ft9+RGyPxOvsuZAWAZ2+ZDRQRHpx8RRmQ3TcDuRmiKchioizT+CR2bO3dsKJIGg==
  template:
    metadata:
      creationTimestamp: null
      name: mongosecret
      namespace: pablogarin

